In [1]:
import numpy as np 
import pandas as pd
import math


<h1>Question 1 - Taylor Series</h1>

In [2]:
def Taylor(x, n):
    sin = 0
    for i in range(n):
        coef = (-1)**i
        num = (2*x)**((2*i)+1)
        denom = math.factorial((2*i)+1)
        sin += (coef)*((num)/(denom))
    
    return sin

rad=math.radians(45)
VA=np.float128(Taylor(rad,5))
VE=np.float128(1.0)
#Absolute error = |VA-VE|
absolute=abs(VA-VE)
#Percentage error (%) = (|VA-VE|/VE) x 100
percentage=(absolute/VE)*100
#Relative Error = Absolute error/VA
relative=absolute/VA
print(f'Rounding ERROR\n\nAbsolute : {absolute}\nPercentage : %{percentage}\nRelative : {relative}')

Rounding ERROR

Absolute : 3.542584286142514e-06
Percentage : %0.0003542584286142514
Relative : 3.5425717362835482e-06


<h1>Question 2 - Gauss Elemination</h1>

In [3]:
A=np.array([[2,-3,-1],[3,2,-5],[2,4,-1]],float)
b=np.array([3,-9,-5],float)

In [4]:
def Gauss(A, b):
    n=len(b)

    for i in range(n-1):
        for j in range(i+1,n):
            if A[j][i]==0:
                continue
            fact=A[i][i]/A[j][i]
            for k in range(i,n):
                A[j][k]=A[i][k]-(fact*A[j][k])
            b[j]=b[i]-(fact*b[j])
            
    for i in range (n):
        b[i]=b[i]/A[i][i]
        A[i]=A[i]/A[i][i]

    x=np.linalg.solve(A,b)

    return x,A,b

In [5]:
x,C,D=Gauss(A,b)

print(f'x1, x2, x3 = {x}\n\n')
print('A matrix\n',C)
print('B matrix\n',D)

x1, x2, x3 = [ 0.65306122 -1.14285714  1.73469388]


A matrix
 [[ 1.         -1.5        -0.5       ]
 [-0.          1.         -0.53846154]
 [ 0.          0.          1.        ]]
B matrix
 [ 1.5        -2.07692308  1.73469388]


<h1>Question 3 - Doolittle Decomposition</h1>

In [6]:
A=np.array([[2.34,-4.10,1.78],[-1.98,3.47,-2.22],[2.36,-15.17,6.18]])
B=np.array([0.02,-0.73,-6.63])
C=np.array([[2,-1,-2],[-4,6,3],[-4,-2,8]])
D=np.array([-1,13,-6])

In [7]:
def Doolittle(A, B):    
    n=len(B)
    lower = np.zeros(n*n).reshape((n,n))
    upper = np.zeros(n*n).reshape((n,n))

    for i in range(n):
        
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
            upper[i][k] = A[i][k] - sum
 
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1
            else:
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
                lower[k][i] = (A[k][i] - sum) / upper[i][i]
    
    y=np.linalg.solve(lower,B)

    x=np.zeros(n,float)
    for i in range(n-1,-1,-1):
        sum=0
        for j in range(i+1,n):
            sum = sum + upper[i,j]*x[j]
        x[i]=(np.array(y)[i]-sum)/upper[i,i]
    

    print(f'x1, x2, x3 : {x}')    
    print("\n")
    print(f'y1, y2, y3 : {y}')
    print("\n")
    print(f'Lower\n{lower}')
    print("\n")
    print(f'Upper\n{upper}')
 

In [8]:
Doolittle(A,B)


x1, x2, x3 : [1. 1. 1.]


y1, y2, y3 : [ 2.00000000e-02 -7.13076923e-01 -1.02360556e+04]


Lower
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.46153846e-01  1.00000000e+00  0.00000000e+00]
 [ 1.00854701e+00 -1.43454444e+04  1.00000000e+00]]


Upper
[[ 2.34000000e+00 -4.10000000e+00  1.78000000e+00]
 [ 0.00000000e+00  7.69230769e-04 -7.13846154e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.02360556e+04]]


<h1>Question 4 - Cholesky Decomposition</h1>

In [9]:
A=np.array([[1,1,1],[1,2,2],[1,2,3]],float)
B=np.array([1,1.5,3],float)


In [10]:
def Cholesky(A,B):
    n = len(A)
    lower = np.zeros(n*n).reshape((n,n))
    transpose = np.zeros(n*n).reshape((n,n))
    n = len(lower)
    for i in range(n):
        for j in range(i+1):
            if i==j:
                val = A[i,i] - np.sum(np.square(lower[i,:i]))
                if val<0:
                    return 0.0
                lower[i,i] = np.sqrt(val)
            else:
                lower[i,j] = (A[i,j] - np.sum(lower[i,:j]*lower[j,:j]))/lower[j,j]
    
    y=np.linalg.solve(lower,B)

    for i in range(n):
        for j in range(n):
            transpose[i][j]=lower[j][i]    
    x=np.linalg.solve(transpose,y)
    print(f'x1, x2, x3 : {x}')    
    print("\n")
    print(f'y1, y2, y3 : {y}')
    print("\n")    
    print(f'Lower\n{lower}')
    print("\n")
    print(f'Transpose\n{transpose}')


In [11]:
Cholesky(A,B)

x1, x2, x3 : [ 0.5 -1.   1.5]


y1, y2, y3 : [1.  0.5 1.5]


Lower
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


Transpose
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
